### ISSUE TITLE
VpDeployment EnvVars valueFrom reduced to {}

### ISSUE THREAD

**Issue by van-vliet** [fintechstudios/ververica-platform-k8s-operator#151]
**Describe the bug**
EnvVars on VpDeployments are not correctly added to the Ververica platform when an environment variable references a Kubernetes secret.

**To Reproduce**
1. Apply resource 
```
apiVersion: ververicaplatform.fintechstudios.com/v1beta2
kind: VpDeployment
metadata:
  name: "secret-loading-fails"
spec:
  deploymentTargetName: default
  metadata:
    namespace: default
  spec:
    state: RUNNING
    upgradeStrategy:
      kind: STATEFUL
    restoreStrategy:
      kind: LATEST_STATE
    maxJobCreationAttempts: 4
    maxSavepointCreationAttempts: 4
    template:
      spec:
        artifact:
          jarUri: "https://repo1.maven.org/maven2/org/apache/flink/flink-examples-streaming_2.12/1.10.1/flink-examples-streaming_2.12-1.10.1-TopSpeedWindowing.jar"
          kind: JAR
        kubernetes:
          pods:
            envVars:
              - name: MY_SECRET_VALUE
                valueFrom:
                  secretKeyRef:
                    name: my-secret
                    key: secretkey
        parallelism: 1
        numberOfTaskManagers: 1
        resources:
          jobmanager:
            cpu: "300m"
            memory: "512m"
          taskmanager:
            cpu: "300m"
            memory: "1024m"
```
2. Open the Ververica Platform UI -> click on the deployment called "secret-loading-fails" -> Configure Deployment ->  select YAML tab.
3. In the spec, the environment variables "valueFrom" is reduced to {}.
```
      kubernetes:
        pods:
          envVars:
            - name: MY_SECRET_VALUE
              valueFrom: {}
```

**Expected behavior**
I expected the Ververica Platform UI to show the following snippet as part of the deployment YAML.
```
            envVars:
              - name: MY_SECRET_VALUE
                valueFrom:
                  secretKeyRef:
                    name: my-secret
                    key: secretkey
```

**Versions (please complete the following information):**
 - Kubernetes: AWS EKS 1.15
 - Ververica Platform: 2.1.1
 - Ververica Platform Operator: v0.8.0
 - Helm, if applicable: Helm chart version 0.12.0
